language: csharp
solution: ./GladBehaviour.sln
sudo: required

install:
  - sudo apt-get install nunit-console
  - nuget restore ./GladBehaviour.sln -ConfigFile NuGet.config

before_script:
  - chmod +x ./tests/RunTests.sh
  - chmod +x ./Build.sh

script:
  - ./Build.sh
  - cd "$TRAVIS_BUILD_DIR/tests"
  - ./RunTests.sh
  - cd "$TRAVIS_BUILD_DIR"